import { Brain, FileText, Receipt, Zap, Target, TrendingUp } from "lucide-react";

import { Badge } from "@components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@components/ui/card";
import { Progress } from "@components/ui/progress";

interface AIAnalyticsCardProps {
  data: {
    total_receipt_metadata: number;
    total_line_items: number;
    ai_generated_line_items: number;
    manual_line_items: number;
    ai_generation_rate: number;
    avg_confidence_score: number;
  };
}

export function AIAnalyticsCard({ data }: Readonly<AIAnalyticsCardProps>) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-blue-600" />
          AI Analytics
        </CardTitle>
        <CardDescription>
          Insights into AI-powered receipt processing and line item generation
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {/* Receipt Metadata */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Receipt className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm font-medium">Receipts Processed</span>
            </div>
            <div className="text-2xl font-bold">{data.total_receipt_metadata}</div>
            <p className="text-xs text-muted-foreground">AI-analyzed receipts</p>
          </div>

          {/* Total Line Items */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm font-medium">Total Line Items</span>
            </div>
            <div className="text-2xl font-bold">{data.total_line_items}</div>
            <p className="text-xs text-muted-foreground">All line items</p>
          </div>

          {/* AI Generated */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-green-600" />
              <span className="text-sm font-medium">AI Generated</span>
            </div>
            <div className="text-2xl font-bold text-green-600">{data.ai_generated_line_items}</div>
            <p className="text-xs text-muted-foreground">Auto-generated items</p>
          </div>

          {/* Manual */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Target className="h-4 w-4 text-orange-600" />
              <span className="text-sm font-medium">Manual Entry</span>
            </div>
            <div className="text-2xl font-bold text-orange-600">{data.manual_line_items}</div>
            <p className="text-xs text-muted-foreground">Manually added items</p>
          </div>
        </div>

        <div className="space-y-4">
          {/* AI Generation Rate */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-blue-600" />
                <span className="text-sm font-medium">AI Generation Rate</span>
              </div>
              <Badge variant="secondary" className="text-xs">
                {data.ai_generation_rate.toFixed(1)}%
              </Badge>
            </div>
            <Progress value={data.ai_generation_rate} className="h-2" />
            <p className="text-xs text-muted-foreground">
              Percentage of line items automatically generated by AI
            </p>
          </div>

          {/* Average Confidence */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Brain className="h-4 w-4 text-purple-600" />
                <span className="text-sm font-medium">Average Confidence Score</span>
              </div>
              <Badge variant="secondary" className="text-xs">
                {data.avg_confidence_score.toFixed(1)}%
              </Badge>
            </div>
            <Progress value={data.avg_confidence_score} className="h-2" />
            <p className="text-xs text-muted-foreground">
              Average confidence level of AI receipt analysis
            </p>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid gap-2 rounded-lg bg-muted p-4">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Efficiency Gain:</span>
            <span className="font-medium">
              {data.total_line_items > 0
                ? `${Math.round((data.ai_generated_line_items / data.total_line_items) * 100)}% automation`
                : "N/A"}
            </span>
          </div>
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Processing Quality:</span>
            <span className="font-medium">
              {data.avg_confidence_score >= 90
                ? "Excellent"
                : data.avg_confidence_score >= 80
                  ? "Good"
                  : data.avg_confidence_score >= 70
                    ? "Fair"
                    : "Needs Review"}
            </span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
